name             'myapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures myapp'
long_description 'Installs/Configures myapp'
version          '0.1.0'

depends 'ruby_rbenv', '~> 1.0.1'
depends 'ruby_build', '~> 0.8.0'
