name             'myapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'MIT'
description      'Installs/Configures myapp'
long_description 'Installs/Configures myapp'
version          '0.1.0'
